name: Build

on: [push, pull_request]

jobs:
  theos:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Theos
        uses: Randomblock1/theos-action@v1

      - name: Build package
        run: make package

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          path: ./packages/com.beeper.beepserv_*.deb
          name: phone-registration-provider
          if-no-files-found: error
